"""recreate missing migration

Revision ID: 116cac07c375
Revises: b5673a2fb4e6
Create Date: 2025-05-09 04:39:54.543831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116cac07c375'
down_revision: Union[str, None] = 'b5673a2fb4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_tasks_id'), 'saved_tasks', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('taskid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('taskid')
    )
    op.create_index(op.f('ix_tasks_taskid'), 'tasks', ['taskid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_taskid'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_saved_tasks_id'), table_name='saved_tasks')
    op.drop_table('saved_tasks')
    # ### end Alembic commands ###
