"""name

Revision ID: 76c5d5b4a690
Revises: cd17a61500ad
Create Date: 2025-05-10 21:32:09.343992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c5d5b4a690'
down_revision: Union[str, None] = 'cd17a61500ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_tasks', sa.Column('taskidbyfrontend', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('taskidbyfrontend', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'taskidbyfrontend')
    op.drop_column('saved_tasks', 'taskidbyfrontend')
    # ### end Alembic commands ###
