"""updated default values

Revision ID: a3d7a9912d84
Revises: 5ba2d4da9d8c
Create Date: 2025-04-16 16:18:40.268650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d7a9912d84'
down_revision: Union[str, None] = '5ba2d4da9d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'language')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'github_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###
