"""name

Revision ID: b3aa9e0fcaf2
Revises: 76c5d5b4a690
Create Date: 2025-05-10 22:20:19.794433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3aa9e0fcaf2'
down_revision: Union[str, None] = '76c5d5b4a690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_tasks', 'taskidbyfrontend',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'taskidbyfrontend',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'taskidbyfrontend',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('saved_tasks', 'taskidbyfrontend',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
