"""add Task and SavedTask models

Revision ID: b5673a2fb4e6
Revises: b5dece4e9238
Create Date: 2025-05-09 04:16:33.507398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5673a2fb4e6'
down_revision: Union[str, None] = 'b5dece4e9238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_tasks_id'), 'saved_tasks', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('taskid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('taskid')
    )
    op.create_index(op.f('ix_tasks_taskid'), 'tasks', ['taskid'], unique=False)
    op.drop_index('ix_pending_users_id', table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('email', name='pending_users_email_key')
    )
    op.create_index('ix_pending_users_id', 'pending_users', ['id'], unique=False)
    op.drop_index(op.f('ix_tasks_taskid'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_saved_tasks_id'), table_name='saved_tasks')
    op.drop_table('saved_tasks')
    # ### end Alembic commands ###
