"""name

Revision ID: caff2a4483ce
Revises: b3aa9e0fcaf2
Create Date: 2025-05-12 04:06:40.823240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caff2a4483ce'
down_revision: Union[str, None] = 'b3aa9e0fcaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_tasks', 'taskidbyfrontend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_tasks', sa.Column('taskidbyfrontend', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
