"""removed column email-verified

Revision ID: fafe608d263c
Revises: 625f159d724e
Create Date: 2025-04-16 17:58:54.183940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafe608d263c'
down_revision: Union[str, None] = '625f159d724e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('pending_users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('pending_users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('pending_users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('pending_users', sa.Column('otp', sa.String(), nullable=False))
    op.add_column('pending_users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pending_users_id'), 'pending_users', ['id'], unique=False)
    op.create_unique_constraint(None, 'pending_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_users', type_='unique')
    op.drop_index(op.f('ix_pending_users_id'), table_name='pending_users')
    op.drop_column('pending_users', 'created_at')
    op.drop_column('pending_users', 'otp')
    op.drop_column('pending_users', 'hashed_password')
    op.drop_column('pending_users', 'username')
    op.drop_column('pending_users', 'email')
    op.drop_column('pending_users', 'id')
    # ### end Alembic commands ###
